language: python
branches:
  only:
  - master
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- pelican content -o output -s pelicanconf.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  target_branch: gh-pages
  on:
    branch: master
